parakeet.txt

i think we should include info about birds

adds parakeet file which describes on trait of parakeets

---

002-hands-on-exercises/01-about/oralordos.txt

I have added my file for the first Ninja level hands-on exercise.

Added Oralordos first exercise

---

002-hands-on-exercises/01-about/goestoeleven.txt

This is the "about me" for Todd McLeod on github @GoesToEleven

hands on exercise ninja 01 #01 for goestoeleven about

---

002-hands-on-exercises/02-humble/oralordos-humble.txt

Added my opinion on what humble means for the Ninja Exercise 01-02.

Added Ninja Exercise level 01 #2 for Oralordos

---

002-hands-on-exercises/02-humble/goestoeleven-humble2.txt

the second file for goestoeleven for ninja 01 #02

hands on project ninja 01 #02 second goestoeleven file

---

002-hands-on-exercises/03-purpose/temp-todd-mcleod-purpose.txt

thanks for this class. having fun. learning a lot. it's awesome.

ninja level 01 ex #03 temp-todd-mcleod purpose text file

---

002-hands-on-exercises/01-about/kind84.txt

Hello from Paolo

---

002-hands-on-exercises/01-about/nazevedo3.txt

Completing hands on exercise number one!  Thank you for all your courses Todd.  They've had tremendous impact on me and inspired me to jump from Network to Software Engineering.
I look forward to seeing you speak at the Silicon Valley Code Camp this weekend!

About Nathan

---

002-hands-on-exercises/01-about/kind84.txt
002-hands-on-exercises/02-humble/kind84-humble.txt

Paolo's humble

---

002-hands-on-exercises/01-about/brennschlus.txt

added txt file, an introduction from Brennschlus

Hands-on exercise #1

---

002-hands-on-exercises/01-about/brennschlus.txt
002-hands-on-exercises/02-humble/brennschlus-humble.txt

Adding my perspective to being humble.

Hands-on exercise #2

---

002-hands-on-exercises/01-about/brian-d-albrecht.txt
002-hands-on-exercises/03-purpose/brian-d-albrecht-purpose.txt

Added an introduction to the 002-hands-on-exercises/01-about section for the first exercise.

Added brian-d-albrecht.txt

---

002-hands-on-exercises/01-about/brian-d-albrecht.txt
002-hands-on-exercises/02-humble/brian-d-albrecht-humble.txt

Adding file for Hands-on Exercise #2.

Adding file brian-d-albrecht-myhumble.txt

---

002-hands-on-exercises/01-about/db325.txt

pusing file

---

002-hands-on-exercises/01-about/billyice.txt
002-hands-on-exercises/02-humble/billyice-humble.txt

Thank you for the nice class so far!!  Here is some of my info. If you ever need a program to for parsing these files up into some sort of database or data structure, let me know. I'd be glad to help.

adding file to introduce myself to this class

---

002-hands-on-exercises/01-about/shawnwollenberg.txt

adding my info @shawnwollenberg

adding my info shawnwollenberg

---

002-hands-on-exercises/01-about/ramirezra.txt

Created ramirezra.txt file and filled out the file according to the instructions.

Added ramirezra.txt file to repository

---

002-hands-on-exercises/02-humble/shawnwollenberg-humble.txt

Added my humble text for shawnwollenberg.

Added my humble text - shawnwollenberg

---

002-hands-on-exercises/02-humble/ramirezra-humble.txt

What humble means to me - Submission for Ninja Exercise 01-02 for ramirezra

ramirezra hands-on-exercise-02-myhumble submission

---

002-hands-on-exercises/01-about/pd222dj.txt

Added short info about me

---

002-hands-on-exercises/01-about/paulofiles.txt

Added a file to introduce myself

Introduction hands-on exercise

---

002-hands-on-exercises/01-about/pystocks.txt

new intro file

---

002-hands-on-exercises/02-humble/paulofiles-humble.txt

Added a file to explain what being humble means

Being humble hands-on exercise

---

002-hands-on-exercises/01-about/cschult.txt

Hi Todd, i like your Go courses. Please add my intro text file to your repo.

add intro text file

---

002-hands-on-exercises/01-about/osariel.txt
002-hands-on-exercises/02-humble/osariel-humble.txt

Being humble is difficult. Sometimes, in an attempt to be humble, I display crass egotism.

Ninja Hands-on excersises #2 Myhumble

---

002-hands-on-exercises/01-about/JayneJacobs.txt
002-hands-on-exercises/02-humble/JayneJacobs-humble.txt
002-hands-on-exercises/03-purpose/JayneJacobs-purpose.txt

Having a bit of trouble figuring out how to  make sure my fork is in step with  this repo.

Adding a bit about myself in JayneJacobs.txt

---

002-hands-on-exercises/01-about/YvesJudeMatta.txt
002-hands-on-exercises/02-humble/YvesJudeMatta-humble.txt
002-hands-on-exercises/03-purpose/YvesJudeMatta-purpose.txt

Add file about myself to follow ninja exercises

add exercises to obtain ninja level 1

---

002-hands-on-exercises/01-about/sebagalan.txt
002-hands-on-exercises/03-purpose/sebagalan-purpose.txt

Hands on exercise #1 #2 #3

---

002-hands-on-exercises/01-about/senny-matrix.txt
002-hands-on-exercises/02-humble/senny-matrix-humble.txt
002-hands-on-exercises/03-purpose/senny-matrix-purpose.txt

Added Senny-Matrix Info

---

002-hands-on-exercises/01-about/manfredkogler.txt
002-hands-on-exercises/02-humble/manfredkogler-humble.txt
002-hands-on-exercises/03-purpose/manfredkogler-purpose.txt

added intro of manfredkogler

---

002-hands-on-exercises/01-about/bugul-noz.txt

Added my information to provided template. Enjoying the class!

Following along with first hands-on

---

002-hands-on-exercises/01-about/tamdc2704.txt
002-hands-on-exercises/02-humble/tamdc2704-humble.txt
002-hands-on-exercises/03-purpose/tamdc2704-purpose.txt

Ninja Exercise - 002 - 01 | 02 | 03

---

002-hands-on-exercises/01-about/dani-santos-code.txt
002-hands-on-exercises/03-purpose/dani-santos-code.txt

Adding a little intro as a way to practice and say hello to you! :)

introduce myself

---

002-hands-on-exercises/01-about/dani-santos-code.txt
002-hands-on-exercises/02-humble/dani-santos-code-humble.txt

This is what I think being humble is

My Humble Definition

---

002-hands-on-exercises/01-about/imattf.txt

**Hands-on exercise 1** 
adding my imattf.txt file

added imattf.txt

---

002-hands-on-exercises/01-about/imattf.txt

Adding imattf-purpose.txt from my updated forked master branch.

Retry on Hands-on exercise 3

---

002-hands-on-exercises/01-about/ei09010.txt
002-hands-on-exercises/02-humble/ei09010-humble.txt
002-hands-on-exercises/03-purpose/ei09010-purpose.txt

Learning Go, thank you for the great and insightful teaching

add my description because im doing an udemy course

---

002-hands-on-exercises/01-about/ei09010.txt
002-hands-on-exercises/02-humble/ei09010-humble.txt

Ei09010 humble

---

002-hands-on-exercises/01-about/dearrudam.txt
002-hands-on-exercises/02-humble/dearrudam-humble.txt

Added my opinion on what humble means for the Ninja Hands-on exercise 2

Added dearrudam's response about being humble meaning for the Ninja Hands-on exercise 2

---

002-hands-on-exercises/01-about/kwifrench.txt

Enjoying the course to date and adding this intro file!

Introducing myself

---

002-hands-on-exercises/01-about/AndyAllin01.txt

First exercise in Todd collaborating course

added about me text file

---

002-hands-on-exercises/02-humble/kwifrench-humble.txt

Adding my humble file for the assignment!

kwifrench-humble commit for Ninja 1-2

---

002-hands-on-exercises/01-about/hauk3wu1ff.txt
002-hands-on-exercises/03-purpose/hauk3wu1ff-purpose.txt

Added hauk3wu1ff.txt about-me file

Added hauk3wu1ff.txt about-me file

---

002-hands-on-exercises/01-about/jpeeling13.txt
002-hands-on-exercises/02-humble/jpeeling13-humble.txt
002-hands-on-exercises/03-purpose/jpeeling13-purpose.txt

I added this new file which conforms to the 000-TEMPLATE-about-me.txt template file and contains data about myself, in accordance to the instructions for Hands-on exercise #1.

added new file for Hands-on exercise #1

---

002-hands-on-exercises/01-about/jpeeling13.txt
002-hands-on-exercises/02-humble/jpeeling13-humble.txt

Added the new humble file with my definition of what I think being humble means.

Added new file for Hands-on exercise #2

---

002-hands-on-exercises/01-about/liberate111.txt
002-hands-on-exercises/02-humble/liberate111-humble.txt
002-hands-on-exercises/03-purpose/liberate111-purpose.txt

added about me #hands-on-1

---

002-hands-on-exercises/01-about/git-aks.txt
002-hands-on-exercises/02-humble/git-aks-humble.txt

Adding my version of humble, `git-aks-humble.txt`, as part of the Ninja Level 01, hands-on exercise 2.

Pull myhumble branch for Ninja level 1 exercise 2

---

002-hands-on-exercises/01-about/git-aks.txt
002-hands-on-exercises/03-purpose/git-aks-purpose.txt

Adding the solution to the `Ninja level 1`, `hands-on exercise 1`, of `Collaboration and Crawling W/ Google's Go (Golang) Language` course on Udemy.
@git-aks
Adding purpose for hands-on exercise #3

Hands-on exercise 1 and 3 Ninja Level 1

---

002-hands-on-exercises/01-about/ChristianoGGuerra.txt

Added a file ChristianoGGuerra.txt with my information, it was the Hands-on exercise #1

Added about me file with personal information in it

---

002-hands-on-exercises/02-humble/christianogguerra-humble.txt
002-hands-on-exercises/03-purpose/christianogguerra-purpose.txt

Added a file christianogguerra-humble.txt that has what humble mean for me, it was the Hands-on exercise #2

Added humble file that has my opnion about whant humble mean

---

002-hands-on-exercises/01-about/sagar424.txt
002-hands-on-exercises/03-purpose/sagar424-purpose.txt

Hi Todd / Contributors,
I created a copy of 01-about file as per the hands on exercise 1 for Ninja level 1. Creating the pull request as a part of the same exercise.

Created sagar424 copy of about file

---

002-hands-on-exercises/01-about/alibaihaqi.txt

Just added my file for the first Ninja Level 1 hands-on exercise

Added ali first exercise

---

002-hands-on-exercises/01-about/alibaihaqi.txt
002-hands-on-exercises/02-humble/alibaihaqi-humble.txt

Give my option on what humble means for the Ninja Exercise Level 01 #02

Added Ninja level 1 hands-on exercise #2

---

002-hands-on-exercises/01-about/janosnanai.txt
002-hands-on-exercises/03-purpose/janosnanai-purpose.txt

Added my file as first exercise.

added first exercise

---

002-hands-on-exercises/01-about/s-hammon.txt

Add s-hammon.txt
